# coding: utf-8

"""
    Stitch Connect

    https://www.stitchdata.com/docs/developers/stitch-connect/api  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import stitch_connect_client
from stitch_connect_client.models.connection_step_props_any_of import ConnectionStepPropsAnyOf  # noqa: E501
from stitch_connect_client.rest import ApiException


class TestConnectionStepPropsAnyOf(unittest.TestCase):
    """ConnectionStepPropsAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectionStepPropsAnyOf(self):
        """Test ConnectionStepPropsAnyOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = stitch_connect_client.models.connection_step_props_any_of.ConnectionStepPropsAnyOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
