# coding: utf-8

"""
    Stitch Connect

    https://www.stitchdata.com/docs/developers/stitch-connect/api  # noqa: E501

    The version of the OpenAPI document: 0.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import stitch_connect_client
from stitch_connect_client.models.google_analytics_source_form_properties_report_definitions import (  # noqa: E501
    GoogleAnalyticsSourceFormPropertiesReportDefinitions,
)
from stitch_connect_client.rest import ApiException


class TestGoogleAnalyticsSourceFormPropertiesReportDefinitions(unittest.TestCase):
    """GoogleAnalyticsSourceFormPropertiesReportDefinitions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGoogleAnalyticsSourceFormPropertiesReportDefinitions(self):
        """Test GoogleAnalyticsSourceFormPropertiesReportDefinitions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = stitch_connect_client.models.google_analytics_source_form_properties_report_definitions.GoogleAnalyticsSourceFormPropertiesReportDefinitions()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
