# coding: utf-8

"""
    Stitch Connect

    https://www.stitchdata.com/docs/developers/stitch-connect/api  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import stitch_connect_client
from stitch_connect_client.api.destinations_api import DestinationsApi  # noqa: E501
from stitch_connect_client.rest import ApiException


class TestDestinationsApi(unittest.TestCase):
    """DestinationsApi unit test stubs"""

    def setUp(self):
        self.api = (
            stitch_connect_client.api.destinations_api.DestinationsApi()
        )  # noqa: E501

    def tearDown(self):
        pass

    def test_create_destination(self):
        """Test case for create_destination

        Creates a new destination. Only a single destination is supported per Stitch client account.   # noqa: E501
        """
        pass

    def test_delete_destination(self):
        """Test case for delete_destination

        Deletes an existing destination. Note: Stitch requires a destination to replicate data. Replication will be paused until a new destination is created and has a successful connection.   # noqa: E501
        """
        pass

    def test_get_destination_types(self):
        """Test case for get_destination_types

        Retrieves general information about the configuration required for all supported destination types.   # noqa: E501
        """
        pass

    def test_get_destinations(self):
        """Test case for get_destinations

        Lists the destination currently in use for a Stitch account. Only a single data warehouse is supported per Stitch client account.   # noqa: E501
        """
        pass

    def test_update_destination(self):
        """Test case for update_destination

        Updates an existing destination. Modifications to the type attribute are not supported.   # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
