# coding: utf-8

"""
    Stitch Connect

    https://www.stitchdata.com/docs/developers/stitch-connect/api  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import stitch_connect_client
from stitch_connect_client.models.create_destination_body import CreateDestinationBody  # noqa: E501
from stitch_connect_client.rest import ApiException


class TestCreateDestinationBody(unittest.TestCase):
    """CreateDestinationBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateDestinationBody(self):
        """Test CreateDestinationBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = stitch_connect_client.models.create_destination_body.CreateDestinationBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
