# coding: utf-8

"""
    Stitch Connect

    https://www.stitchdata.com/docs/developers/stitch-connect/api  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import stitch_connect_client
from stitch_connect_client.models.field_level_metadata import (  # noqa: E501
    FieldLevelMetadata,
)
from stitch_connect_client.rest import ApiException


class TestFieldLevelMetadata(unittest.TestCase):
    """FieldLevelMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldLevelMetadata(self):
        """Test FieldLevelMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = stitch_connect_client.models.field_level_metadata.FieldLevelMetadata()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
