# coding: utf-8

"""
    Stitch Connect

    https://www.stitchdata.com/docs/developers/stitch-connect/api  # noqa: E501

    The version of the OpenAPI document: 0.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import stitch_connect_client
from stitch_connect_client.models.mixpanel_source_form_properties import (  # noqa: E501
    MixpanelSourceFormProperties,
)
from stitch_connect_client.rest import ApiException


class TestMixpanelSourceFormProperties(unittest.TestCase):
    """MixpanelSourceFormProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMixpanelSourceFormProperties(self):
        """Test MixpanelSourceFormProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = stitch_connect_client.models.mixpanel_source_form_properties.MixpanelSourceFormProperties()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
